ports:
  - port: 8100
    name: Collaboration Server
    onOpen: notify

tasks:
  - init: |
      npm install
      npm run build
    command: |
      export OCT_ACTIVATE_SIMPLE_LOGIN=true
      npm run start
