name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Use Node.js 18.x
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        shell: bash
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint

  build:
    name: Build (${{ matrix.os }}, node-18)

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Use Node.js 18.x
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        shell: bash
        run: |
          npm install

      - name: Build
        shell: bash
        run: |
          npm run build

